name: Deploy the docs to RTD

on:
  push:
    branches: [ main ]
    paths:  # 当更改以下文件时，会触发Actions更新文档
      - 'sphinx_readthedocs_test/**'
      - '.github/workflows/deploy_docs_to_rtd.yml'
      - 'README.md'

env:
  REPO_HTTPS: https://github.com/Phoenix0qi/sphinx_readthedocs_test.git
  CLONE_URL: ${{ github.event.repository.clone_url }}
  USER_NAME: ${{ github.event.repository.owner.name }}
  USER_EMAIL: ${{ github.event.repository.owner.email }}
  SUBMMIT_BRANCH: docs
  PACKAGE_NAME: sphinx_readthedocs_test

jobs:
  Deploy_TO_RTD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
          architecture: 'x64'

      - name: Prepare docs directory
        run: |
          mkdir -p docs_build
          # cp -r your_package docs_build/ || true
          cp -r source docs_build/source || true
          cp README.md docs_build/ || true
          cp requirements.txt docs_build/ || true

      - name: Setup git config
        run: |
          git config --global user.email $USER_EMAIL
          git config --global user.name $USER_NAME
      - name: Push to docs branch
        run: |
          cd docs_build
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -B docs
          git add .
          git commit -m "Update docs from main $(date)"
          git push -f origin docs